class: QQMonitorRobot.java MsnMonitorRobot.java
	/usr/java/jdk/bin/javac -Xlint:unchecked -cp .:../../javaLib/LumaQQ.jar:../../javaLib/jiwaiMessage.jar QQMonitorRobot.java
	/usr/java/jdk/bin/javac -cp .:../../javaLib/cindy.jar:../../javaLib/commons-logging.jar:../../javaLib/jml-1.0b1.jar:../../javaLib/jiwaiMessage.jar MsnMonitorRobot.java

clean:
	rm *.class
