#!/bin/bash
PWD=/opt/jiwai.de/nonweb/crobot/lucene
PATH=/bin:/usr/bin:/usr/java/jdk/bin

JAVALIB=/opt/jiwai.de/javaLib
INDEXPATH=/opt/lucene/index

STEP=100
let "MAX = $1 + 0"
let "FROM = $MAX - 100"

cd $PWD

java -cp .:${JAVALIB}/jiwai-library-1.2.jar:${JAVALIB}/lucene-core-2.0.0.jar:${JAVALIB}/mysql-connector-java.jar Index ${INDEXPATH}/status_${MAX} status $FROM $MAX 

cd $OLDPWD
