#!/bin/bash
PWD=/opt/jiwai.de/nonweb/crobot/lucene
PATH=/bin:/usr/bin:/usr/java/jdk/bin

JAVALIB=/opt/jiwai.de/javaLib
INDEXPATH=/opt/lucene/index

NOW=`date +%s`
INDEX=$1

cd ${PWD}

# TEST
if [ ! $INDEX ]; then
    exit;
fi

# DIR Rotation
INDEXDIR=${INDEXPATH}/${INDEX}
SEARCHDIR=${INDEXPATH}/${INDEX}s

TEMPDIR=${INDEXPATH}/${INDEX}.${NOW}
TEMPDIRS=${TEMPDIR}s

# Increment UPDATE
mv /tmp/update_${INDEX} /tmp/update_${INDEX}_temp
cat /tmp/update_${INDEX}_temp | sort | uniq > /tmp/update_${INDEX}_u
java -cp .:${JAVALIB}/jiwai-library-1.2.jar:${JAVALIB}/lucene-core-2.0.0.jar:${JAVALIB}/mysql-connector-java.jar Increment ${INDEXDIR} ${INDEX}
rm -rf /tmp/update_${INDEX}_*

#CD Work Directory
cp -R ${INDEXDIR} ${TEMPDIR}

java -cp .:${JAVALIB}/jiwai-library-1.2.jar:${JAVALIB}/lucene-core-2.0.0.jar:${JAVALIB}/mysql-connector-java.jar Optimize ${TEMPDIR}

# CP BACK
mv ${SEARCHDIR} ${TEMPDIRS}
mv ${TEMPDIR} ${SEARCHDIR}
rm -rf ${TEMPDIRS}
