run: QQJiWaiRobot.class
	/usr/java/jdk1.5.0_11/bin/java -cp LumaQQ.jar:log4j.jar:. -Dqq.no=229516989 -Dqq.pass=Beta@JiWai741de QQJiWaiRobot

QQJiWaiRobot.class: QQJiWaiRobot.java
	/usr/java/jdk1.5.0_11/bin/javac -cp LumaQQ.jar:log4j.jar:. QQJiWaiRobot.java

clean:
	rm *.class

