QQJiWaiRobot.class: QQJiWaiRobot.java
	/usr/java/jdk1.5.0_11/bin/javac -cp LumaQQ.jar:log4j.jar:. QQJiWaiRobot.java

clean:
	rm *.class

run:
	/usr/java/jdk1.5.0_11/bin/java -cp LumaQQ.jar:log4j.jar:. -Dqq.no=520656 -Dqq.pass=pianziji QQJiWaiRobot
