## NOTE: DO NOT FORGET THE BLANKET [] IF YOU WANNAR TAG IT

%feedMap = (
    'uefa'          => {
        'nameScreen'=> 'uefa@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/ecup.xml',
    },
    'premier.league'=> {
        'nameScreen'=> 'premier.league@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/yingchao.xml',
    },
    'serie.a'       => {
        'nameScreen'=> 'serie.a@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/yijia.xml',
    },
    'la.liga'       => {
        'nameScreen'=> 'la.liga@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/xijia.xml',
    },
    'realmadrid'    => {
        'nameScreen'=> 'real.madrid@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/huangma.xml',
    },
    'barcelona'     => {
        'nameScreen'=> 'barcelona@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/bacailona.xml',
    },
    'acmilan'       => {
        'nameScreen'=> 'acmilan@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/ac.xml',
    },
    'intermilan'    => {
        'nameScreen'=> 'intermilan@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/guomidongtai.xml',
    },
    'juventus'      => {
        'nameScreen'=> 'juventus@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/youwendongtai.xml',
    },
    'manchester'    => {
        'nameScreen'=> 'manchester@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/manlian.xml',
    },
    'chelsea'       => {
        'nameScreen'=> 'chelsea@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/qieerxi.xml',
    },
    'arsenal'       => {
        'nameScreen'=> 'arsenal@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/asenna.xml',
    },
    'tom.pop'       => {
        'nameScreen'=> 'tom.pop@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.tom.com/ent/pop.xml',
    },
    'sohu.astro'    => {
        'nameScreen'=> 'sohu.astro@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://astro.women.sohu.com/rss/xingzuoxinwen.xml',
    },
    'thinkgeek'     => {
        'nameScreen'=> 'thinkgeek',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.thinkgeek.com/thinkgeek.rss',
    },
    'geek.com'      => {
        'nameScreen'=> 'geek.com',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.geek.com/feed/',
    },
    'asus'          => {
        'nameScreen'=> 'asus2008',
        'nameFull'  => '',
        'password'  => 'a361dde1.de',
        'feedUrl'   => 'http://event.feedsky.com/asus/blog/feed',
    },
    'newsmth'   => {
        'nameScreen'=> 'newsmth',
        'nameFull'  => '[水木社区]',
        'password'  => 'newsmthbbsdem1ma',
        'feedUrl'   => 'http://www3.newsmth.net/rssi.php?h=1',
    },
    'slashdot'  => {    ## GFWed
        'nameScreen'=> 'slashdot',
        'nameFull'  => '[slashdot]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.slashdot.org/Slashdot/slashdot',
    },
    'freshmeat' => {    ## Too much
        'nameScreen'=> 'freshmeat',
        'nameFull'  => '[freshmeat]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds.pheedo.com/freshmeatnet_announcements_global',
    },
    'sourceforge'   => {
        'nameScreen'=> 'sourceforge',
        'nameFull'  => '[sourceforge]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds.pheedo.com/sourceforgenet_news',
    },
    'engadget'      => {
        'nameScreen'=> 'engadget',
        'nameFull'  => '[瘾科技]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://cn.engadget.com/rss.xml',
    },
    'youkuhot'      => {
        'nameScreen'=> 'youkuhot',
        'nameFull'  => '[优酷]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.youku.com/index/rss_cool_v/',
        'filter'    => 's/www\.youku/v\.youku/gi',
        'ratelimit' => 1,
    },
    'fedora'        => {
        'nameScreen'=> 'fedora',
        'nameFull'  => '[fedora]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://planet.fedoraproject.org/rss20.xml',
    },
    'microsoft'     => {
        'nameScreen'=> 'microsoft',
        'nameFull'  => '[microsoft]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://planet.fedoraproject.org/rss20.xml',
    },
    'msdn'          => {
        'nameScreen'=> 'msdn',
        'nameFull'  => '[msdn]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.microsoft.com/feeds/MSDN/globalfeeds/en-us/Global-MSDN-en-us.xml',
    },
    'dw-world'      => {
        'nameScreen'=> 'dw-world',
        'nameFull'  => '[德国之声]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://rss.dw-world.de/rdf/rss-chi-all',
        'filter'    => 's/\?maca=chi-rss-chi-all-\d+-rdf//g',
    },
    'edu2do'        => {
        'nameScreen'=> 'edu2do',
        'nameFull'  => '[益学会]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://edu2do.com/blog/feed/',
    },
    'memedia'       => {
        'nameScreen'=> 'memedia.cn',
        'nameFull'  => '[草莓周刊]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://memedia.cn/feed/',
    },
    'twitter'       => {
        'nameScreen'=> 'twitter',
        'nameFull'  => '[MicroBlogging]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://feeds.feedburner.com/TwitterBlog',
        'version'   => 1,
    },
    'jaiku'         => {
        'nameScreen'=> 'jaiku',
        'nameFull'  => '[MicroBlogging]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://www.jaiku.com/blog/feed/',
    },
    'google'        => {
        'nameScreen'=> 'googleblog',
        'nameFull'  => '[Google]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://feeds.feedburner.com/blogspot/MKuf',
        'version'   => 1,
        'redirect'  => 'feedburner',
    },
    'googlecode'    => {
        'nameScreen'=> 'googlecode',
        'nameFull'  => '[Google]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://feeds.feedburner.com/blogspot/Dcni',
        'version'   => 1,
        'redirect'  => 'feedburner',
    },
    'ftchinese'     => {
        'nameScreen'=> 'ftchinese',
        'nameFull'  => '[News]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.ftchinese.com/sc/rss_s.jsp',
        'version'   => 1,
    },
    'jiwaiblog'     => {
        'nameScreen'=> 'blog',
        'password'  => 'JiWaidem1ma',
        'feedUrl'   => 'http://blog.jiwai.de/index.php/feed',
    },
    'dellstore'     => {
        'nameScreen'=> '戴尔中文博客',
        'password'  => 'zhou@dell',
        'feedUrl'   => 'http://chinese.direct2dell.com/rss.aspx',
        'roi'       => 'description',
        'version'   => 1,
    },
    'lastfm'        => {
        'nameScreen'=> 'Last.fm',
        'password'  => 'lastfmdem1ma',
        'feedUrl'   => 'http://blog.last.fm/atom/',
        'version'   => 1,
    },
    'lastfmblog'    => {
        'nameScreen'=> 'Last.fm中文博客',
        'password'  => 'lastfmdem1ma',
        'feedUrl'   => 'http://blog.sina.com.cn/rss/lastFM.xml',
        'version'   => 1,
    },
    'steve.jobs'    => {
        'nameScreen'=> 'steve.jobs',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'https://poxy.dotft.com/tunnel.php?broken=http://feeds.feedburner.com/thesecretdiaryofstevejobs',
        'version'   => 1,
        'redirect'  => 'feedburner',
    },
    'openfire'      => {
        'nameScreen'=> 'openfire',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.igniterealtime.org/community/blogs/ignite/feeds/tags/openfire',
    },
    '39'            => {
        'nameScreen'=> '39健康网',
        'nameFull'  => '[健康]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.39.net/rss.xml',
        'ratelimit' => 20,
    },
    'xinhua.native' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[国内]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/native.xml',
    },
    'xinhua.world'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[国际]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/world.xml',
    },
    'xinhua.fortune'=> {
        'nameScreen'=> '新华网',
        'nameFull'  => '[财经]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/fortune.xml',
    },
    'xinhua.sports' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[体育]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/sports.xml',
    },
    'xinhua.ent'    => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[文娱]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/ent.xml',
    },
    'xinhua.mil'    => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[军事]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/mil.xml',
    },
    'xinhua.it'     => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[IT新闻]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/it.xml',
    },
    'xinhua.science'=> {
        'nameScreen'=> '新华网',
        'nameFull'  => '[科技]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/science.xml',
    },
    'xinhua.edu'    => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[教育]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/edu.xml',
    },
    'xinhua.photos' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[图片]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/photos.xml',
    },
    'xinhua.legal'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[法治]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/legal.xml',
    },
    'xinhua.forum'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[新华论坛]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/forum/forum.xml',
    },
    'xinhua.lady'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[女性]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/lady.xml',
    },
    'xinhua.video'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[视频]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/video.xml',
    },
    'xinhua.auto'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[汽车]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/autonews.xml',
    },
    'xinhua.stock'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[金融]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/stock.xml',
    },
    'xinhua.health' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[健康]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/health.xml',
    },
    'xinhua.travel' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[旅游]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/travel.xml',
    },
    'xinhua.food'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[饮食]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/food.xml',
    },
    'xinhua.employ' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[职场]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/employment.xml',
    },
    'xinhua.book'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[读书]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/book.xml',
    },
    'xinhua.school' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[校园]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/school.xml',
    },
    'xinhua.english'=> {
        'nameScreen'=> '新华网',
        'nameFull'  => '[英文新闻]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/english.xml',
    },
    'xinhua.xhcm'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[新华传媒]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/xhcm.xml',
    },
    'xinhua.hyyw'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[娱乐]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/hyyw.xml',
    },
    'xinhua.xhzl'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[新华资料]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/xhzl.xml',
    },
);

