## NOTE: DO NOT FORGET THE BLANKET [] IF YOU WANNAR TAG IT
## $Id$

%feedMap = (
    'glabs'         => {
        'nameScreen'=> 'googlelabs',
        'nameFull'  => '[Google]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.googlelabs.com/rss',
        'version'   => 1,
    }, 
    'facebook'      => {
        'nameScreen'=> 'facebook',
        'nameFull'  => '[SNS]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://blog.facebook.com/atom.php',
        'version'   => 1,
    }, 
    'qt'            => {
        'nameScreen'=> 'trolltech',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://labs.trolltech.com/blogs/feed/',
        'version'   => 1,
    }, 
    'gemag'         => {
        'nameScreen'=> 'gemag',
        'nameFull'  => '[商业]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.gemag.com.cn/gemag/new/rss2.asp',
        'version'   => 1,
    }, 
    'henhuang'      => {
        'nameScreen'=> 'henhuanghenbaoli',
        'nameFull'  => '[少儿不宜]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds2.feedburner.com/henhuanghenbaoli',
        'version'   => 1,
        'redirect'  => 'feedburner',
    }, 
    'chinasmack'    => {
        'nameScreen'=> 'chinasmack',
        'nameFull'  => '[英语]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feedproxy.google.com/chinaSMACK',
        'version'   => 1,
    }, 
### Music
    'ms.coldplay'   => {
        'nameScreen'=> 'coldplay',
        'nameFull'  => '[band]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://news.google.cn/news?hl=zh-CN&ned=ccn&q=coldplay&ie=UTF-8&output=rss',
    },
### IT
    'it.yesky'      => {
        'nameScreen'=> 'yesky',
        'nameFull'  => '[IT业界]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://www.chinabyte.com/index.xml',
    },
    'it.zdnet'      => {
        'nameScreen'=> 'zdnet',
        'nameFull'  => '[IT业界]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://news.zdnet.com/2504-1_22-0-20.xml',
    },
    'it.zend'       => {
        'nameScreen'=> 'zend',
        'nameFull'  => '[php]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://www.zend.com/en/company/news/event/feed',
        'version'   => 1,
    },
    'it.php'        => {
        'nameScreen'=> 'php.net',
        'nameFull'  => '[php]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://cn2.php.net/feed.atom',
        'version'   => 1,
    },
    'it.gnome'      => {
        'nameScreen'=> 'gnome',
        'nameFull'  => '[linux]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://gnomedesktop.org/node/feed',
    },
    'it.kde'        => {
        'nameScreen'=> 'kde.org',
        'nameFull'  => '[linux]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://www.kde.org/dotkdeorg.rdf',
    },
    'it.linuxcom'   => {
        'nameScreen'=> 'linux.com',
        'nameFull'  => '[linux]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://www.linux.com/feature/?theme=rss',
    },
    'it.kernel'     => {
        'nameScreen'=> 'kerneltrap',
        'nameFull'  => '[linux]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://kerneltrap.org/node/feed',
    },
    'it.secunia'    => {
        'nameScreen'=> 'secunia',
        'nameFull'  => '[security]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://secunia.com/information_partner/anonymous/o.rss',
    },
    'it.nvd'        => {
        'nameScreen'=> 'nvd.nist',
        'nameFull'  => '[security]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://nvd.nist.gov/download/nvd-rss.xml',
    },
### baidu
    'bd.internet'   => {
        'nameScreen'=> 'baidu.news@jiwai.de',
        'nameFull'  => '[互联网]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://news.baidu.com/n?cmd=1&class=internet&tn=rss&sub=0',
    },
    'bd.internet2'  => {
        'nameScreen'=> 'baidu.news@jiwai.de',
        'nameFull'  => '[互联网]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://news.baidu.com/n?cmd=4&class=internet&tn=rss',
    },
### tencent
    'tc.tennis'     => {
        'nameScreen'=> 'tencent@jiwai.de',
        'nameFull'  => '[网球]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://sports.qq.com/qqtennis/rss_tennis.xml',
    },
    'tc.csocce'     => {
        'nameScreen'=> 'tencent@jiwai.de',
        'nameFull'  => '[中国足球]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://sports.qq.com/csocce/rss_csocce.xml',
    },
    'tc.isocce'     => {
        'nameScreen'=> 'tencent@jiwai.de',
        'nameFull'  => '[国际足球]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://sports.qq.com/isocce/rss_isocce.xml',
    },
    'tc.basket'     => {
        'nameScreen'=> 'tencent@jiwai.de',
        'nameFull'  => '[篮球]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://sports.qq.com/basket/rss_basket.xml',
    },
    'tc.race'       => {
        'nameScreen'=> 'tencent@jiwai.de',
        'nameFull'  => '[赛车]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://sports.qq.com/qqf1/rss_qqf1.xml',
    },
### sina blog
    'sb.cul'        => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[文化]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/cul.xml',
    },
    'sb.exc'        => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[独家]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/exc.xml',
    },
    'sb.feel'       => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[情感]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/feel.xml',
    },
    'sb.ent'        => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[八卦]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/ent.xml',
    },
    'sb.enjoy'      => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[生活记录]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/enjoy.xml',
    },
    'sb.other'      => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[观点]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/other.xml',
    },
    'sb.finance'    => {
        'nameScreen'=> 'sina.blog@jiwai.de',
        'nameFull'  => '[产经]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.sina.com.cn/blog/index/finance.xml',
    },
### video
    'youkuhot'      => {
        'nameScreen'=> 'youkuhot',
        'nameFull'  => '[优酷]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.youku.com/index/rss_cool_v/',
        'filter'    => 's/www\.youku/v\.youku/gi',
        'ratelimit' => 1,
    },
    'youtubehot'    => {
        'nameScreen'=> 'youtubehot',
        'nameFull'  => '[视频]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://youtube.com/rss/global/top_viewed_today.rss',
        'filter'    => 's/\?v=/v\//gi',
        'ratelimit' => 1,
    },
    'pomohohot'    => {
        'nameScreen'=> '汪强',
        'nameFull'  => '[视频]',
        'password'  => '888888',
        'feedUrl'   => 'http://z.jiwai.de/3.xml',
        #'feedUrl'   => 'http://search.pomoho.com/videodata/dvodvideo_20081008.xml',
        'filter'    => 's/\?v=/v\//gi',
        'ratelimit' => 1,
    },
### douban
    'douban.movie'  => {
        'nameScreen'=> 'review.movie@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.douban.com/feed/review/movie',
        'version'   => 1,
    },
    'douban.music'  => {
        'nameScreen'=> 'review.music@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.douban.com/feed/review/music',
        'version'   => 1,
    },
    'douban.book'   => {
        'nameScreen'=> 'review.book@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.douban.com/feed/review/book',
        'version'   => 1,
    },
### sports
    'race'          => {
        'nameScreen'=> 'race@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/saiche.xml',
    },
    'tennis'        => {
        'nameScreen'=> 'tennis@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/wangqiu.xml',
    },
    'tabletennis'   => {
        'nameScreen'=> 'tabletennis@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/pingping.xml',
    },
    'volley'        => {
        'nameScreen'=> 'volleyball@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/paiqiu.xml',
    },
### soccer
    'zhongchao'     => {
        'nameScreen'=> 'zhongchao@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/zhongchao.xml',
    },
    'bundesliga'    => {
        'nameScreen'=> 'bundesliga@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/dejia.xml',
    },
    'uefa'          => {
        'nameScreen'=> 'uefa@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/ecup.xml',
    },
    'premier.league'=> {
        'nameScreen'=> 'premier.league@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/yingchao.xml',
    },
    'serie.a'       => {
        'nameScreen'=> 'serie.a@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/yijia.xml',
    },
    'la.liga'       => {
        'nameScreen'=> 'la.liga@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://rss.sports.sohu.com/rss/xijia.xml',
    },
    'realmadrid'    => {
        'nameScreen'=> 'real.madrid@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/huangma.xml',
    },
    'barcelona'     => {
        'nameScreen'=> 'barcelona@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/bacailona.xml',
    },
    'acmilan'       => {
        'nameScreen'=> 'acmilan@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/ac.xml',
    },
    'intermilan'    => {
        'nameScreen'=> 'intermilan@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/guomidongtai.xml',
    },
    'juventus'      => {
        'nameScreen'=> 'juventus@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/youwendongtai.xml',
    },
    'manchester'    => {
        'nameScreen'=> 'manchester@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/manlian.xml',
    },
    'chelsea'       => {
        'nameScreen'=> 'chelsea@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/qieerxi.xml',
    },
    'arsenal'       => {
        'nameScreen'=> 'arsenal@jiwai.de',
        'nameFull'  => '',
        'password'  => 'sportdem1ma',
        'feedUrl'   => 'http://sports.sohu.com/rss/asenna.xml',
    },
### soccer end
    'tom.pop'       => {
        'nameScreen'=> 'tom.pop@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.tom.com/ent/pop.xml',
    },
    'sohu.astro'    => {
        'nameScreen'=> 'sohu.astro@jiwai.de',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://astro.women.sohu.com/rss/xingzuoxinwen.xml',
    },
    'thinkgeek'     => {
        'nameScreen'=> 'thinkgeek',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.thinkgeek.com/thinkgeek.rss',
    },
    'geek.com'      => {
        'nameScreen'=> 'geek.com',
        'nameFull'  => '',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.geek.com/feed/',
    },
    'asus'          => {
        'nameScreen'=> 'asus2008',
        'nameFull'  => '',
        'password'  => 'a361dde1.de',
        'feedUrl'   => 'http://event.feedsky.com/asus/blog/feed',
    },
    'newsmth'   => {
        'nameScreen'=> 'newsmth',
        'nameFull'  => '[水木社区]',
        'password'  => 'newsmthbbsdem1ma',
        'feedUrl'   => 'http://www3.newsmth.net/rssi.php?h=1',
    },
    'slashdot'  => {    ## GFWed
        'nameScreen'=> 'slashdot',
        'nameFull'  => '[slashdot]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.slashdot.org/Slashdot/slashdot',
    },
    'phpdeveloper'  => {
        'nameScreen'=> 'phpdeveloper',
        'nameFull'  => '[php]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.phpdeveloper.org/feed',
    },
    'freshmeat' => {    ## Too much
        'nameScreen'=> 'freshmeat',
        'nameFull'  => '[freshmeat]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds.pheedo.com/freshmeatnet_announcements_global',
    },
    'sourceforge'   => {
        'nameScreen'=> 'sourceforge',
        'nameFull'  => '[sourceforge]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds.pheedo.com/sourceforgenet_news',
    },
    'engadget'      => {
        'nameScreen'=> 'engadget',
        'nameFull'  => '[瘾科技]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://cn.engadget.com/rss.xml',
    },
    'fedora'        => {
        'nameScreen'=> 'fedora',
        'nameFull'  => '[linux]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://planet.fedoraproject.org/rss20.xml',
    },
    'opensolaris'   => {
        'nameScreen'=> 'opensolaris',
        'nameFull'  => '[opensource]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://opensolaris.org/jive/rss/rssmessages.jspa?forumID=76',
    },
    'suse'          => {
        'nameScreen'=> 'suse',
        'nameFull'  => '[linux]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://news.opensuse.org/feed/',
    },
    'kubuntu'       => {
        'nameScreen'=> 'kubuntu',
        'nameFull'  => '[linux]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.kubuntu.org/kubuntu.rss',
        'version'   => 1,
        'ratelimit' => 50,
    },
    'gentoo'        => {
        'nameScreen'=> 'gentoo',
        'nameFull'  => '[linux]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.gentoo.org/rdf/en/gentoo-news.rdf',
        'version'   => 1,
    },
    'adobe.lab'     => {
        'nameScreen'=> 'adobe',
        'nameFull'  => '[lab]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://weblogs.macromedia.com/labs/index.xml',
    },
    'adobe.flex'    => {
        'nameScreen'=> 'adobe',
        'nameFull'  => '[flex]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.adobe.com/en/resources_flex.rss',
    },
    'adobe.flash'   => {
        'nameScreen'=> 'adobe',
        'nameFull'  => '[flash]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.adobe.com/en/resources_flash.rss',
    },
    'symbian'       => {
        'nameScreen'=> 'symbian',
        'nameFull'  => '[mobile]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.allaboutsymbian.com/news/rss2all.xml',
    },
    'mininova'      => {
        'nameScreen'=> 'mininova',
        'nameFull'  => '[bittorrent]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.mininova.org/rss.xml',
    },
    'meebo'         => {
        'nameScreen'=> 'meebo',
        'nameFull'  => '[Meebo]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://blog.meebo.com/?feed=rss2',
    },
    'verycd'        => {
        'nameScreen'=> 'verycd',
        'nameFull'  => '[emule]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://lib.verycd.com/feeds/rss.xml',
    },
    'microsoft'     => {
        'nameScreen'=> 'microsoft',
        'nameFull'  => '[microsoft]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://planet.fedoraproject.org/rss20.xml',
    },
    'msdn'          => {
        'nameScreen'=> 'msdn',
        'nameFull'  => '[msdn]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.microsoft.com/feeds/MSDN/globalfeeds/en-us/Global-MSDN-en-us.xml',
    },
    'dw-world'      => {
        'nameScreen'=> 'dw-world',
        'nameFull'  => '[德国之声]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.dw-world.de/rdf/rss-chi-all',
        'filter'    => 's/\?maca=chi-rss-chi-all-\d+-rdf//g',
    },
    'edu2do'        => {
        'nameScreen'=> 'edu2do',
        'nameFull'  => '[益学会]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://edu2do.com/blog/feed/',
    },
    'memedia'       => {
        'nameScreen'=> 'memedia.cn',
        'nameFull'  => '[草莓周刊]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://memedia.cn/feed/',
    },
    'twitter'       => {
        'nameScreen'=> 'twitter',
        'nameFull'  => '[MicroBlogging]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds.feedburner.com/TwitterBlog',
        'version'   => 1,
    },
    'jaiku'         => {
        'nameScreen'=> 'jaiku',
        'nameFull'  => '[MicroBlogging]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.jaiku.com/blog/feed/',
    },
    'google'        => {
        'nameScreen'=> 'googleblog',
        'nameFull'  => '[Google]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feedproxy.google.com/blogspot/MKuf',
        'version'   => 1,
        'redirect'  => 'feedburner',
    },
    'youtube'       => {
        'nameScreen'=> 'youtubeblog',
        'nameFull'  => '[youtube]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://youtube.com/rss/global/our_blog.rss',
    },
    'googlecode'    => {
        'nameScreen'=> 'googlecode',
        'nameFull'  => '[Google]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feedproxy.google.com/blogspot/Dcni',
        'version'   => 1,
        'redirect'  => 'feedburner',
    },
    'ftchinese'     => {
        'nameScreen'=> 'ftchinese',
        'nameFull'  => '[News]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.ftchinese.com/rss/rss_s.php',
        'version'   => 1,
    },
    'jiwaiblog'     => {
        'nameScreen'=> 'blog',
        'password'  => 'JiWaidem1ma',
        #'feedUrl'   => 'http://blog.jiwai.de/index.php/feed',
        'feedUrl'   => 'http://feed.blog.jiwai.de/',
    },
    'dellstore'     => {
        'nameScreen'=> '戴尔中文博客',
        'password'  => 'zhou@dell',
        'feedUrl'   => 'http://chinese.direct2dell.com/rss.aspx',
        'roi'       => 'description',
        'version'   => 1,
    },
    'dellcoupon1'    => {
        'nameScreen'=> 'Zhou.jacqui@gmail.com',
        'nameFull'  => '[折扣][笔记本]',
        'password'  => 'zhou@dell',
        'feedUrl'   => 'http://www1.ap.dell.com/content/rss/promos.aspx?c=cn&cid=promo_notebook_rss&cs=cndhs1&l=zh&s=dhs',
        'roi'       => 'description',
        'version'   => 1,
    },
    'dellcoupon2'    => {
        'nameScreen'=> 'Zhou.jacqui@gmail.com',
        'nameFull'  => '[折扣][台式机]',
        'password'  => 'zhou@dell',
        'feedUrl'   => 'http://www1.ap.dell.com/content/rss/promos.aspx?c=cn&cid=promo_desktop_rss&cs=cndhs1&l=zh&s=dhs',
        'roi'       => 'description',
        'version'   => 1,
    },
    'dellcoupon3'    => {
        'nameScreen'=> 'Zhou.jacqui@gmail.com',
        'nameFull'  => '[折扣][外设]',
        'password'  => 'zhou@dell',
        'feedUrl'   => 'http://www1.ap.dell.com/content/rss/promos.aspx?c=cn&cid=promo_snp_rss&cs=cndhs1&l=zh&s=dhs',
        'roi'       => 'description',
        'version'   => 1,
    },
    'dellcoupon4'    => {
        'nameScreen'=> 'Zhou.jacqui@gmail.com',
        'nameFull'  => '[折扣]',
        'password'  => 'zhou@dell',
        'feedUrl'   => 'http://www1.ap.dell.com/content/rss/promos.aspx?c=cn&cid=promo_misc_rss&cs=cndhs1&l=zh&s=dhs',
        'roi'       => 'description',
        'version'   => 1,
    },
    'lastfm'        => {
        'nameScreen'=> 'Last.fm',
        'password'  => 'lastfmdem1ma',
        'feedUrl'   => 'http://blog.last.fm/atom/',
        'version'   => 1,
    },
    'lastfmblog'    => {
        'nameScreen'=> 'Last.fm中文博客',
        'password'  => 'lastfmdem1ma',
        'feedUrl'   => 'http://blog.sina.com.cn/rss/lastFM.xml',
        'version'   => 1,
    },
    'steve.jobs'    => {
        'nameScreen'=> 'steve.jobs',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://feeds.feedburner.com/thesecretdiaryofstevejobs',
        'version'   => 1,
        'redirect'  => 'feedburner',
    },
    'openfire'      => {
        'nameScreen'=> 'openfire',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.igniterealtime.org/community/blogs/ignite/feeds/tags/openfire',
    },
    'danwei'        => {
        'nameScreen'=> 'danwei',
        'nameFull'  => '[Web2.0]',
        'password'  => 'bulkdem1ma',
        'feedUrl'   => 'http://feedproxy.google.com/DanweiRss10',
        'version'   => 1,
    }, 
    'mtime'         => {
        'nameScreen'=> 'mtime',
        'nameFull'  => '[Web2.0]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.mtime.com/rss/news.rss',
        'version'   => 1,
    }, 
    'douban'        => {
        'nameScreen'=> 'douban',
        'nameFull'  => '[Web2.0]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://blog.douban.com/feed/',
        'version'   => 1,
    }, 
    'sogou'         => {
        'nameScreen'=> 'sogou',
        'nameFull'  => '[Web2.0]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://labs.blog.sohu.com/rss',
        'version'   => 1,
    }, 
    'justsoit'      => {
        'nameScreen'=> 'justsoit',
        'nameFull'  => '[山寨]',
        'password'  => 'shanzhaidem1ma',
        'feedUrl'   => 'http://justsoit.yo2.cn/feed',
        'version'   => 1,
    }, 
    'justsoit-rss'  => {
        'nameScreen'=> 'justsoit',
        'nameFull'  => '[山寨]',
        'password'  => 'shanzhaidem1ma',
        'feedUrl'   => 'http://justsoit.com/rss/justsoit/',
        'version'   => 1,
        'ratelimit' => 2,
    }, 
    'mysql'         => {
        'nameScreen'=> 'mysql',
        'nameFull'  => '[MySQL]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.mysql.com/mysql.rss',
        'version'   => 1,
    }, 
    'mysql-dev'     => {
        'nameScreen'=> 'mysql',
        'nameFull'  => '[MySQL]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://dev.mysql.com/mysql.rss',
        'version'   => 1,
    }, 
    'mysql-ha'      => {
        'nameScreen'=> 'mysql',
        'nameFull'  => '[MySQL]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://mysqlha.blogspot.com/feeds/posts/default?alt=rss',
        'version'   => 1,
    }, 
    '39'            => {
        'nameScreen'=> '39健康网',
        'nameFull'  => '[健康]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.39.net/rss.xml',
        'ratelimit' => 20,
    },
## developerWorks Series
    'dw-web'        => {
        'nameScreen'=> 'developerWorks',
        'nameFull'  => '[webdev]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.ibm.com/developerworks/views/web/rss/libraryview.jsp',
        'version'   => 1,
    },
    'dw-opensource' => {
        'nameScreen'=> 'developerWorks',
        'nameFull'  => '[opensource]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.ibm.com/developerworks/views/opensource/rss/libraryview.jsp',
        'version'   => 1,
    },
    'dw-linux'      => {
        'nameScreen'=> 'developerWorks',
        'nameFull'  => '[linux]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.ibm.com/developerworks/views/linux/rss/libraryview.jsp',
        'version'   => 1,
    },
    'dw-java'       => {
        'nameScreen'=> 'developerWorks',
        'nameFull'  => '[java]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://www.ibm.com/developerworks/views/java/rss/libraryview.jsp',
        'version'   => 1,
    },
## xinhua series
    'xinhua.native' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[国内]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/native.xml',
    },
    'xinhua.world'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[国际]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/world.xml',
    },
    'xinhua.fortune'=> {
        'nameScreen'=> '新华网',
        'nameFull'  => '[财经]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/fortune.xml',
    },
    'xinhua.sports' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[体育]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/sports.xml',
    },
    'xinhua.ent'    => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[文娱]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/ent.xml',
    },
    'xinhua.mil'    => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[军事]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/mil.xml',
    },
    'xinhua.it'     => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[IT新闻]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/it.xml',
    },
    'xinhua.science'=> {
        'nameScreen'=> '新华网',
        'nameFull'  => '[科技]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/science.xml',
    },
    'xinhua.edu'    => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[教育]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/edu.xml',
    },
    'xinhua.photos' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[图片]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/photos.xml',
    },
    'xinhua.legal'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[法治]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/legal.xml',
    },
    'xinhua.forum'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[新华论坛]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/forum/forum.xml',
    },
    'xinhua.lady'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[女性]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/lady.xml',
    },
    'xinhua.video'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[视频]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/video.xml',
    },
    'xinhua.auto'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[汽车]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/autonews.xml',
    },
    'xinhua.stock'  => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[金融]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/stock.xml',
    },
    'xinhua.health' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[健康]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/health.xml',
    },
    'xinhua.travel' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[旅游]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/travel.xml',
    },
    'xinhua.food'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[饮食]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/food.xml',
    },
    'xinhua.employ' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[职场]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/employment.xml',
    },
    'xinhua.book'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[读书]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/book.xml',
    },
    'xinhua.school' => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[校园]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/school.xml',
    },
    'xinhua.english'=> {
        'nameScreen'=> '新华网',
        'nameFull'  => '[英文新闻]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/english.xml',
    },
    'xinhua.xhcm'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[新华传媒]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/xhcm.xml',
    },
    'xinhua.hyyw'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[娱乐]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/hyyw.xml',
    },
    'xinhua.xhzl'   => {
        'nameScreen'=> '新华网',
        'nameFull'  => '[新华资料]',
        'password'  => 'geekdem1ma',
        'feedUrl'   => 'http://rss.xinhuanet.com/rss/xhzl.xml',
    },
);

