<?php
// wikka.config.php written at Sun May 13 19:49:09 2007
// do not change wikka_version manually!

$wakkaConfig = array(
	'mysql_host' => 'localhost',
	'mysql_database' => 'jiwai_wikka',
	'mysql_user' => 'jiwai_wikka',
	'table_prefix' => 'wikka_',
	'root_page' => 'JiWaiHelp',
	'wakka_name' => '[[JiWaiHelp 叽歪de]]',
	'base_url' => 'http://help.jiwai.de/',
	'rewrite_mode' => '1',
	'wiki_suffix' => '@jiwai_wikka',
	'action_path' => 'actions',
	'handler_path' => 'handlers',
	'gui_editor' => '1',
	'stylesheet' => 'wikka.css',
	'wikka_formatter_path' => 'formatters',
	'wikka_highlighters_path' => 'formatters',
	'geshi_path' => '3rdparty/plugins/geshi',
	'geshi_languages_path' => '3rdparty/plugins/geshi/geshi',
	'header_action' => 'header',
	'footer_action' => 'footer',
	'navigation_links' => '[[CategoryCategory 分类]] :: [[FAQs 常见问题]] :: [[PageIndex 帮助列表]] ',
	'logged_in_navigation_links' => '[[CategoryCategory 分类]] :: [[PageIndex 帮助列表]] :: [[RecentChanges 最近更新]] :: [[RecentlyCommented 最新评论]] :: [[UserSettings 用户设置]]',
	'referrers_purge_time' => '30',
	'pages_purge_time' => '0',
	'xml_recent_changes' => '10',
	'hide_comments' => '1',
	'require_edit_note' => '0',
	'anony_delete_own_comments' => '1',
	'public_sysinfo' => '0',
	'double_doublequote_html' => 'safe',
	'external_link_tail' => '<span class="exttail">&#8734;</span>',
	'sql_debugging' => '0',
	'admin_users' => 'ZiXia',
	'admin_email' => 'zixia@zixia.net',
	'upload_path' => 'uploads',
	'mime_types' => 'mime_types.txt',
	'geshi_header' => 'div',
	'geshi_line_numbers' => '1',
	'geshi_tab_width' => '4',
	'grabcode_button' => '1',
	'wikiping_server' => '',
	'default_write_acl' => '+',
	'default_read_acl' => '*',
	'default_comment_acl' => '+',
	'wakka_version' => '1.1.6.3',
	'mysql_password' => 'WiJiWaiKka_1!',
	'meta_keywords' => '叽歪de,帮助,叽叽歪歪,唧唧歪歪,jiwai,jijiwaiwai,jjww',
	'meta_description' => '叽歪de帮助，包含详细的手机短信、MSN、Gtalk、QQ、API等说明内容。');
?>
